# GENERAL

title:               Git Micrometer
tagline:             'Measure your git commits'
description:         'Provides a summary of individuals contribution to a repo.'
url:                 ngeorge.us/git_micrometer
author:
  name:              Nate George
  url:               ngeorge.us/git_micrometer

# MENU

menu:
  - href:			/
    text:			Home
    icon:     home
  - href:			/blog
    text:			Blog
    icon:     pencil
  - href:			/about
    text:			About
    icon:     info-circle

# SOCIAL

social:
  - href:			#
    icon:			youtube
  - href:			#
    icon:			twitter
  - href:			#
    icon:			github
  - href:			#
    icon:			envelope
  - href:			http://www.yourprojectdomain.com/atom.xml
    icon:			rss

# ACCOUNTS

# webmasterID: 		0000000000000000000000000000000000000000

# OTHER

baseurl:             	/
permalink:           	/blog/:categories/:title/
paginate:				5
paginate_path:			/blog/page:num/
markdown:            	redcarpet
highlighter:         	pygments
